"""Initial migration

Revision ID: 4145cca71c62
Revises: 
Create Date: 2026-07-30 17:56:01.904917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4145cca71c62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plagiarism_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_score', sa.Float(), nullable=True))
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('generated_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('generated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('ai_score')
        batch_op.drop_column('plagiarism_score')

    # ### end Alembic commands ###
